services:
  app:
    build:
      context: .
    command: "bundle exec rails s -b 0.0.0.0"
    depends_on:
      - database
    volumes:
      - ".:/app"
    env_file: .env
    ports:
      - "3000:3000"

  database:
    image: postgres:16-alpine
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

volumes:
  database-data:

